import { mkdir, readFile, writeFile, readdir, unlink, stat, rm } from 'fs/promises'
import { join } from 'path'
import type { CanvasFile } from '../types'
import { projectDataDir } from './projectDataPath'

const CANVASES_SUBDIR = 'canvases'

/** Central asset-dir suffix (canvases/<canvasId>-assets). */
export const CANVAS_ASSETS_SUFFIX = '-assets'

// mime <-> extension whitelist. Pasted/uploaded images are effectively always
// one of these; anything else is rejected rather than guessed at. (Owned here
// since the task-images store was purged — this file is the single import
// surface for canvas-asset handling.)
const MIME_TO_EXT: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
}

/** The on-disk extension for a mime, or null if the type is unsupported. */
export const extForMime = (mime: string): string | null => MIME_TO_EXT[mime] ?? null

// Reverse lookup for read paths. Kept private — callers can't influence the
// allowed extensions through this module.
const EXT_TO_MIME: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  webp: 'image/webp',
}

/** UUID v4 strict. Asset ids are server-generated, but the GET/DELETE paths
 *  echo them from the client and must guard against path traversal. */
export const isValidAssetId = (id: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)

/** Canvas ids are UUIDs generated by canvasData. Loose v4-ish check (canvasData
 *  doesn't enforce the v4 high nibble, so we match any 8-4-4-4-12 hex form). */
export const isValidCanvasId = (id: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)

/** Central asset dir: ~/.openground/projects/<uuid>/canvases/<canvasId>-assets. */
export const centralCanvasAssetsDir = async (projectPath: string, canvasId: string) =>
  join(await projectDataDir(projectPath), CANVASES_SUBDIR, `${canvasId}${CANVAS_ASSETS_SUFFIX}`)

// Canvas image assets live in the project's central data dir.
const assetsDir = (projectPath: string, canvasId: string) =>
  centralCanvasAssetsDir(projectPath, canvasId)

/** Persist an uploaded image's bytes. Throws if the mime type isn't on the
 *  whitelist (MIME_TO_EXT above). */
export const writeCanvasAsset = async (
  projectPath: string,
  canvasId: string,
  assetId: string,
  mime: string,
  data: Buffer,
) => {
  const ext = extForMime(mime)
  if (!ext) throw new Error(`unsupported image type: ${mime}`)
  const dir = await assetsDir(projectPath, canvasId)
  await mkdir(dir, { recursive: true })
  await writeFile(join(dir, `${assetId}.${ext}`), data)
}

/** Read an asset's bytes + mime, or null if it isn't on disk. */
export const readCanvasAsset = async (
  projectPath: string,
  canvasId: string,
  assetId: string,
): Promise<{ data: Buffer; mime: string } | null> => {
  const dir = await assetsDir(projectPath, canvasId)
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return null
  }
  // The extension isn't known up front, so match <assetId>.<knownExt>.
  const match = entries.find((e) => {
    const dot = e.lastIndexOf('.')
    if (dot <= 0 || e.slice(0, dot) !== assetId) return false
    return Boolean(EXT_TO_MIME[e.slice(dot + 1).toLowerCase()])
  })
  if (!match) return null
  const ext = match.slice(match.lastIndexOf('.') + 1).toLowerCase()
  try {
    return { data: await readFile(join(dir, match)), mime: EXT_TO_MIME[ext] }
  } catch {
    return null
  }
}

/** Best-effort delete of an asset by id. Used when the user removes an image
 *  element so the bytes don't sit in the dir waiting for the next prune. */
export const deleteCanvasAsset = async (
  projectPath: string,
  canvasId: string,
  assetId: string,
) => {
  const dir = await assetsDir(projectPath, canvasId)
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return
  }
  const match = entries.find((e) => {
    const dot = e.lastIndexOf('.')
    if (dot <= 0 || e.slice(0, dot) !== assetId) return false
    return Boolean(EXT_TO_MIME[e.slice(dot + 1).toLowerCase()])
  })
  if (!match) return
  try {
    await unlink(join(dir, match))
  } catch {
    /* best-effort */
  }
}

// A freshly uploaded file is kept regardless of references for this long: an
// image upload and the canvas write that references it are two separate
// round-trips, so a save whose payload predates the upload must not reap it.
const GC_MIN_AGE_MS = 2 * 60 * 1000

/** Garbage-collect image files no element references — run after every canvas
 *  write so removing an image element eventually reclaims disk. Never throws. */
export const pruneCanvasAssets = async (
  projectPath: string,
  canvasId: string,
  canvas: CanvasFile,
) => {
  const dir = await assetsDir(projectPath, canvasId)
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return
  }
  const referenced = new Set<string>()
  for (const el of canvas.elements) {
    if (el.type === 'image' && el.assetId) referenced.add(el.assetId)
  }
  const now = Date.now()
  await Promise.all(
    entries.map(async (entry) => {
      const dot = entry.lastIndexOf('.')
      const id = dot > 0 ? entry.slice(0, dot) : entry
      if (referenced.has(id)) return
      const full = join(dir, entry)
      try {
        const info = await stat(full)
        if (now - info.mtimeMs < GC_MIN_AGE_MS) return
        await unlink(full)
      } catch {
        /* best-effort */
      }
    }),
  )
}

/** Wipe the entire assets directory for a canvas. Used when the canvas
 *  itself is deleted via canvasData.deleteCanvas. No-op if the dir was
 *  never created. */
export const deleteCanvasAssetsDir = async (
  projectPath: string,
  canvasId: string,
) => {
  const dir = await assetsDir(projectPath, canvasId)
  try {
    await rm(dir, { recursive: true, force: true })
  } catch {
    /* best-effort */
  }
}
